name = "final-siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true


routes = [

  { pattern = "cf-w.site", custom_domain = true },
  { pattern = "support.zoom.us.cf-w.site", custom_domain = true },
  { pattern = "ava.game.naver.com.cf-w.site", custom_domain = true },
  { pattern = "graph.instagram.com.cf-w.site", custom_domain = true },
  { pattern = "df.game.naver.com.cf-w.site", custom_domain = true },
  { pattern = "zoomgov.com.cf-w.site", custom_domain = true }
  ]

[[kv_namespaces]]
binding = "SIREN"
id = "5684a9ef808a47519728f4906d4e971c"

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "bbbbbbbb-cccc-4ddd-eeee-ffffffffffff"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/FinalSiren/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/FinalSiren/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/FinalSiren/refs/heads/master/web/link.html"
CONVERTER_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/FinalSiren/refs/heads/master/web/converter.html"
